# Generated by Django 4.1.3 on 2023-01-05 12:51

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('bmw', 'BMW'), ('toyota', 'TOYOTA'), ('kia', 'KIA'), ('honda', 'Honda'), ('audi', 'Audi'), ('dodge', 'Dodge'), ('ford', 'Ford'), ('hyundai', 'Hyundai'), ('mazda', 'Mazda'), ('mercedes', 'Mercedes'), ('jeep', 'Jeep'), ('mitsubishi', 'Mitsubishi')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='car',
            name='engine',
            field=models.CharField(default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to=main.utils.upload_image),
        ),
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default=None, max_length=17),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
