# Generated by Django 4.1.3 on 2023-02-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_userslikedcars"),
    ]

    operations = [
        migrations.AddField(
            model_name="userslikedcars",
            name="liked_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
